colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

mainSections = ["posts"]
enableSearch = true
enableCodeCopy = true
defaultBackgroundImage = "img/background.png"

[homepage]
layout = "background"
homepageImage = "img/background.png"
layoutBackgroundBlur = true
showRecent = true
showRecentItems = 3
showMoreLink = false
showMoreLinkDest = "/posts"

[article]
showHero = true
heroStyle = "thumbAndBackground"
layoutBackgroundHeaderSpace = true
showDate = true
showDateUpdated = false
showAuthor = false
showBreadcrumbs = true
showTableOfContents = true
showPagination = true

[list]
showHero = true
heroStyle = "background"
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showSummary = true
groupByYear = true

[footer]
showThemeAttribution = false
