[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.156.0"
  SECRETS_SCAN_OMIT_PATHS = "themes/blowfish/**"

[context.deploy-preview]
  command = "git submodule update --init --recursive && hugo --gc --minify --buildFuture -b \"$DEPLOY_PRIME_URL\""

[context.branch-deploy]
  command = "git submodule update --init --recursive && hugo --gc --minify -b \"$DEPLOY_PRIME_URL\""
